# Generated by Django 4.1.4 on 2023-04-26 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('picture', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('target_client', models.TextField(max_length=255)),
                ('logo', models.BooleanField(default=False)),
                ('pictures_human', models.BooleanField(default=False)),
                ('format_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azure_project_api.format')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Photos_Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azure_project_api.photo')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azure_project_api.tag')),
            ],
        ),
    ]
